\documentclass[letterpaper]{article}
\usepackage[top=.5in,right=.5in,left=.5in,bottom=.5in]{geometry}

\begin{document}
\SweaveOpts{concordance=TRUE}
\setkeys{Gin}{width=\textwidth} %this will make figures use the full width of the page

\begin{center}

<<echo=FALSE,results=hide>>=
require(ggplot2)
require(grid)

theme_update(panel.background=theme_blank(), 
			 panel.grid.major=theme_blank(), 
			 panel.border=theme_blank())

#Borrowed (i.e. stollen) from http://research.stowers-institute.org/efg/R/Color/Chart/ColorChart.R
getColorHexAndDecimal <- function(color) {
	if(is.na(color)) {
		return(NA)
	} else {
		c <- col2rgb(color)
		return(sprintf("#%02X%02X%02X   %3d %3d %3d", c[1],c[2],c[3], c[1], c[2], c[3]))
	}
}

df = data.frame(x=rep(1:26, 26), y=rep(1:26, each=26))
df$c = NA
df[1:length(colors()),'c'] = colors()
df$n = NA
df[1:length(colors()),'n'] = 1:length(colors())
df$r = df$g = df$b = NA
df[1:length(colors()),c('r','g','b')] = t(col2rgb(colors()))
df$text = ifelse(apply(df[,c('r','g','b')], 1, sum) > (255*3/2), 'black', 'white')
df$hex = lapply(df$c, getColorHexAndDecimal)
df$hex2 = paste(format(df$n, width=3), format(df$c, width=(max(nchar(df$c))+1)), format(df$hex, width=(max(nchar(df$hex))+1)))

@

<<fig=TRUE,echo=FALSE,results=hide,width=7.5,height=6.0>>=
print(
ggplot(data=data.frame(x=c(0:25))) + geom_point(size=10, aes(x=x,y=x,shape=x)) + 
	facet_wrap(~ x, scales='free') + xlab('') + ylab('') +
	scale_shape_identity() +
	opts(axis.text.x=theme_blank(), axis.text.y=theme_blank(), 
		axis.ticks=theme_blank(), legend.position='none')
)
@

<<colorgrid,fig=FALSE,echo=FALSE,results=hide>>=
p = ggplot(data=data.frame(x=c(1:6))) + geom_hline(size=2, aes(yintercept=x, linetype=x)) +
	scale_linetype_identity() +
	xlab(NULL) + ylab(NULL) + xlim(c(0,100)) +
	opts(axis.text.x=theme_blank(), axis.ticks=theme_blank(), legend.position='none')
ggsave(plot=p, filename='linetypes.pdf', width=7.5,height=2.5)
@
\includegraphics{linetypes}


<<fig=TRUE,echo=FALSE,results=hide,width=7.5>>=
print(
ggplot(df, aes(x=x, y=y, fill=c, label=n)) + geom_tile() + geom_text(aes(colour=text), size=2) + 
	scale_fill_identity() +
	scale_colour_identity() +
	xlab(NULL) + ylab(NULL) +
	opts(axis.text.x=theme_blank(), axis.ticks=theme_blank(), plot.margin = unit(c(0,0,0,0), "cm"),
		 axis.text.y=theme_blank(), axis.ticks=theme_blank(), legend.position='none')
)
@

\begin{figure}[ht]
\begin{minipage}[b]{0.5\linewidth}
<<fig=TRUE,echo=FALSE,results=hide,width=3.25,height=9>>=
print(
ggplot(df[1:100,], aes(x=1, y=n, fill=c, label=hex2, colour=text)) +
	geom_tile() + geom_text(family = 'mono', size=2) +
	scale_fill_identity() +
	scale_colour_identity() +
	xlab(NULL) + ylab(NULL) +
	opts(axis.text.x=theme_blank(), axis.ticks=theme_blank(), plot.margin = unit(c(0,0,0,0), "cm"),
		 axis.text.y=theme_blank(), axis.ticks=theme_blank(), legend.position='none')
)
@
\end{minipage}
\begin{minipage}[b]{0.5\linewidth}
<<fig=TRUE,echo=FALSE,results=hide,width=3.25,height=9>>=
print(
ggplot(df[101:200,], aes(x=1, y=n, fill=c, label=hex2, colour=text)) +
	geom_tile() + geom_text(family = 'mono', size=2) +
	scale_fill_identity() +
	scale_colour_identity() +
	xlab(NULL) + ylab(NULL) +
	opts(axis.text.x=theme_blank(), axis.ticks=theme_blank(), plot.margin = unit(c(0,0,0,0), "cm"),
		 axis.text.y=theme_blank(), axis.ticks=theme_blank(), legend.position='none')
)
@
\end{minipage}
\end{figure}

\begin{figure}[ht]
\begin{minipage}[b]{0.5\linewidth}
<<fig=TRUE,echo=FALSE,results=hide,width=3.25,height=9>>=
print(
ggplot(df[201:300,], aes(x=1, y=n, fill=c, label=hex2, colour=text)) +
	geom_tile() + geom_text(family = 'mono', size=2) +
	scale_fill_identity() +
	scale_colour_identity() +
	xlab(NULL) + ylab(NULL) +
	opts(axis.text.x=theme_blank(), axis.ticks=theme_blank(), plot.margin = unit(c(0,0,0,0), "cm"),
		 axis.text.y=theme_blank(), axis.ticks=theme_blank(), legend.position='none')
)
@
\end{minipage}
\begin{minipage}[b]{0.5\linewidth}
<<fig=TRUE,echo=FALSE,results=hide,width=3.25,height=9>>=
print(
ggplot(df[301:400,], aes(x=1, y=n, fill=c, label=hex2, colour=text)) +
	geom_tile() + geom_text(family = 'mono', size=2) +
	scale_fill_identity() +
	scale_colour_identity() +
	xlab(NULL) + ylab(NULL) +
	opts(axis.text.x=theme_blank(), axis.ticks=theme_blank(), plot.margin = unit(c(0,0,0,0), "cm"),
		 axis.text.y=theme_blank(), axis.ticks=theme_blank(), legend.position='none')
)
@
\end{minipage}
\end{figure}

\begin{figure}[ht]
\begin{minipage}[b]{0.5\linewidth}
<<fig=TRUE,echo=FALSE,results=hide,width=3.25,height=9>>=
print(
ggplot(df[401:500,], aes(x=1, y=n, fill=c, label=hex2, colour=text)) +
	geom_tile() + geom_text(family = 'mono', size=2) +
	scale_fill_identity() +
	scale_colour_identity() +
	xlab(NULL) + ylab(NULL) +
	opts(axis.text.x=theme_blank(), axis.ticks=theme_blank(), plot.margin = unit(c(0,0,0,0), "cm"),
		 axis.text.y=theme_blank(), axis.ticks=theme_blank(), legend.position='none')
)
@
\end{minipage}
\begin{minipage}[b]{0.5\linewidth}
<<fig=TRUE,echo=FALSE,results=hide,width=3.25,height=9>>=
print(
ggplot(df[501:600,], aes(x=1, y=n, fill=c, label=hex2, colour=text)) +
	geom_tile() + geom_text(family = 'mono', size=2) +
	scale_fill_identity() +
	scale_colour_identity() +
	xlab(NULL) + ylab(NULL) +
	opts(axis.text.x=theme_blank(), axis.ticks=theme_blank(), plot.margin = unit(c(0,0,0,0), "cm"),
		 axis.text.y=theme_blank(), axis.ticks=theme_blank(), legend.position='none')
)
@
\end{minipage}
\end{figure}

\end{center}

\end{document}
